### ISSUE TITLE
Is this supposed to be node compatible, or just used in browser?

### ISSUE THREAD

**Issue by thedevelopnik** [zuffik/mailtrap-client#1]
Hi, this looks like an awesome package and I started using it today, but I'm using it in a Jest test suite, and it's failing because `fetch` is not defined.

Was this intended to be used in a browser runtime, and not Node? Or is there a way to provide fetch in a node runtime that I'm unaware of? Thank you!

**Comment by thedevelopnik** [comment]
I noticed you can provide an HttpProvider, is there a way to use Axios or something similar for that purpose?

Rather I should say, I tried plugging in Axios but couldn't get the types to be compatible.

**Comment by zuffik** [comment]
You can use https://www.npmjs.com/package/node-fetch as polyfill, but sure I can make axios provider.

**Comment by zuffik** [comment]
See #2
